return {
  { "folke/tokyonight.nvim" },
  { "arcticicestudio/nord-vim" },
  { "nvim-lua/plenary.nvim" },
  { "nvim-telescope/telescope.nvim", dependencies = { "nvim-lua/plenary.nvim" } },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "neovim/nvim-lspconfig" },
  { "williamboman/mason.nvim", config = true },
  { "williamboman/mason-lspconfig.nvim" },
  { "hrsh7th/nvim-cmp" },
  { "hrsh7th/cmp-nvim-lsp" },
  { "j-hui/fidget.nvim", tag = "legacy", config = true },
  { "glepnir/lspsaga.nvim", branch = "main", config = true },
  { "olimorris/codecompanion.nvim" },
  { "nvim-lualine/lualine.nvim" },
}
